name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.5.1
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    path: ../

  http: ^1.1.0
  image_picker: ">=1.0.4"
  photo_view: ^0.14.0
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  math_keyboard:
    git:
      url: https://github.com/midchamps/math_keyboard.git
      ref: HEAD
      resolved-ref: 8dd6ce1c4668259c590c68cbf8d1711d59cfef1a
      path: math_keyboard
  universal_html: ^2.2.4

  gal: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

# The following section is specific to Flutter packages.
flutter:
